### ISSUE TITLE
API postcode lookup failing for some blacklisted valid but badly formatted postcodes

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#718]
For example `WR15+ 8NB`. Note that `WR15 8NB` is in the blacklist

`https://wheredoivote.co.uk/api/beta/postcode/WR15+ 8NB.json` causes a 500 with the following stack trace: 

```Internal Server Error: /api/beta/postcode/WR15+ 8NB.json
Traceback (most recent call last):
  File "/var/www/polling_stations/env/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/polling_stations/env/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/polling_stations/env/lib/python3.4/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/polling_stations/env/lib/python3.4/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/polling_stations/env/lib/python3.4/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/polling_stations/code/polling_stations/apps/api/postcode.py", line 91, in retrieve
    council = Council.objects.get(area__covers=location)
  File "/var/www/polling_stations/env/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/polling_stations/env/lib/python3.4/site-packages/django/db/models/query.py", line 325, in get
    clone = self.filter(*args, **kwargs)
  File "/var/www/polling_stations/env/lib/python3.4/site-packages/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/var/www/polling_stations/env/lib/python3.4/site-packages/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/var/www/polling_stations/env/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1310, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/var/www/polling_stations/env/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1338, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/var/www/polling_stations/env/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1156, in build_filter
    value, lookups, used_joins = self.prepare_lookup_value(value, lookups, can_reuse, allow_joins)
  File "/var/www/polling_stations/env/lib/python3.4/site-packages/django/db/models/sql/query.py", line 996, in prepare_lookup_value
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
```

I think this is because we're doing a simple `replace` on `postcode`, rather than the better `re.sub` that we do in the `AddressBaseGeocoder`, so it's including the `+` in the postcode and failing.

**Comment by chris48s** [comment]
Yep - I'd spotted this. Will submit a PR with fix this morning :)
